### ISSUE TITLE
error in npm run dev

### ISSUE THREAD

**Issue by GeniusTian** [poloclub/cnn-explainer#24]
hi 
I ran the project following the conda env (supposedly all dependencies are installed), and I got error like below.

[!] Error: Package subpath './compiler.js' is not defined by "exports" in D:\Users\WangST2\Desktop\workspace\study_dir\cnn-explainer-master\node_modules\svelte\package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './compiler.js' is not defined by "exports" in D:\Users\WangST2\Desktop\workspace\study_dir\cnn-explainer-master\node_modules\svelte\package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\Users\WangST2\Desktop\workspace\study_dir\cnn-explainer-master\node_modules\rollup-plugin-svelte\index.js:11:4)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-app@1.0.0 dev: `rollup -c -w`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-app@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I'm seeking your thoughts on what is going on. No one else seems have this issue.
Thanks for your time answering this.

**Comment by xiaohk** [comment]
Hey! Thanks for notifying us. This seems to be caused by a breaking change of svelte (https://github.com/sveltejs/svelte/issues/5665).

Changing the rollup-plugin-svelte version to 6.1.1 should fix it.

I updated `package.json` in a0f561787846a4a0afd030032822022d53de1019.

Thanks!
